---
---

<link rel="stylesheet" href="styles.css" type="text/css">

My broad research agenda lies at the intersection of International Trade and Industrial Organization. More specifically, I am interested in how firms' decision to fragment production globally has an effect on their R&D choices and how that ultimately affects productivity. Exploring other innovation outcomes, I am also interested in how firms react to opposing forces of trade in the form of import competition and cheaper sourcing of intermediates by patenting and undertaking product/process innovations. I study these research questions empirically using both reduced form and theory backed structural estimation techniques. 

### Work In Progress

The below working papers represent my work to date on the topic of trade, innovation and labor market outcomes:

Productive Offshoring: Evidence from Spain (New version coming soon)

Fragmentation and assembly of production across the globe, popularly referred to as offshoring, is typically associated with lost jobs and displaced workers. However, often ignored is a dimension of productivity-enhancing, within-firm reorganization spurred by offshoring. This paper provides novel evidence that such reorganization can take place in the form of increased innovation and change in firm level employment composition in favor of high-skilled workers. I use firm-level microdata from the manufacturing sector in Spain to construct a plausibly exogenous measure of offshoring. I show that, following the financial crisis of 2008, offshoring has a positive effect on R\&D expenditures and high-skilled employment in Spain. These findings are consistent with a heterogenous firms model where reduction in trade costs affect the productivity of offshoring firms through the intensive margin of technology investments.

[Gender Inequality in the Aftermath of Negative Trade Shocks: Evidence from U.S.](files/Trade_and_Gender_2018_WP.pdf) with M.Larch, I.Murtazashvili and Y.V. Yotov. (Under Review) 

We study the differential post-layoff responses in labor market outcomes for men vs. women when unemployment is caused by international trade. Our paper is the first to capitalize on the richness and unique design of the U.S. Trade Act Participant Report database (in combination with the Trade Adjustment Assistance dataset) in order to analyze gender differentials. The analysis identifies trade-affected workers as an over- looked and vulnerable group with very pronounced gender gaps in earnings. Three main results stand out from our estimates. First, we find that the pre-layoff wage gap between men and women who have lost their jobs due to trade is very wide; a striking 30% premium for men, even after controlling for education, experience, race, and other demographic characteristics. Second, we establish that the success rate in finding em- ployment for women who have been laid off because of trade is not significantly lower as compared to men, however we do observe significant differences across some states and some sectors. Third, our estimates reveal that the pre-layoff wage premium for men is completely eliminated upon re-employment. However, we attribute this result to wage compression. Finally, our data enable us to document a series of gender-related outcomes across demographic characteristics, retraining choices, geography, and sectors.
 


